apiVersion: apps/v1
kind : Deployment
metadata :
  name : metadata-deployment-config-demo
spec :
  replicas : 3
  selector :
    matchLabels:
      app : replica-demo-pods
  template:
    metadata:
      labels:
        app: replica-demo-pods
    spec:
      containers:
      - name: replica-metadata-service-container
        image: poojasub/metadata-service:1.2
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /actuator/info
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 4
        envFrom:
        - configMapRef:
            name: my-config
            optional: true