apiVersion: apps/v1
kind : Deployment
metadata :
  name : mongo-deployment-volume
spec :
  replicas : 1
  selector :
    matchLabels:
      app : mongo-pod
  template:
    metadata:
      labels:
        app: mongo-pod
    spec:
      containers:
      - name: mongo-container
        image: mongo
        ports:
        - containerPort: 27017
        volumeMounts:
          - mountPath: /data/db
            name: mongo-data
      volumes:
        - name: mongo-data
          hostPath:
            path: /home/docker/data/db