kind: Pod
apiVersion: v1
metadata:
  name: nameapp
  labels:
    type: nameapp
spec:
  containers:
    - name: nameapp
      image: poojasub/metadata-service:1.2
      ports:
        - containerPort: 8080
      envFrom:
        - configMapRef:
            name: my-config
            optional: true











            envFrom:
            - configMapRef:
                name: my-config
                optional: true